name: QuizCupRemastered
version: '${project.version}'
main: de.zblubba.quizcupremastered.QuizCupRemastered
api-version: 1.19
authors: [ zBlubba ]
description: Remastered Version of the old QuizCup Plugin
website: https://zblubba.de

commands:
  fly:
    permission: quizcup.helper
    description: Toggles the permission to fly
  spawn:
    description: teleportiert ein spieler zum spawn
  createfrage:
    permission: quizcup.frage.create
    description: erstellt eine frage
  addantwort:
    permission: quizcup.frage.antwort.add
    description: fügt eine Antwort zu einer Frage hinzu
  startfrage:
    permission: quizcup.frage.start
    description: startet eine frage
  closeserver:
    permission: quizcup.close
    description: schließt / oeffnet den server
  closechat:
    permission: quizcup.chat.close
    description: öffnet / schließt den chat
  invis:
    permission: quizcup.visibility
    description: schaltet die sichtbarkeit von Spielern um
  points:
    permission: quizcup.points
    description: setzt oder zeigt die punkte eines spielers an