name: QuizCupRemastered
version: '${project.version}'
main: de.zblubba.quizcupremastered.QuizCupRemastered
api-version: 1.19
authors: [ zBlubba ]
description: Remastered Version of the old QuizCup Plugin
website: https://zblubba.de

commands:
  fly:
    permission: quizcup.helper
    description: Toggles the permission to fly
  spawn:
    description: teleports a player to the spawn
  mysql:
    permission: quizcup.mysql
    description: command for testing purposes only
  createfrage:
    permission: quizcup.frage.create
    description: creates a question
  addantwort:
    permission: quizcup.frage.antwort.add
    description: fügt eine Antwort zu einer Frage hinzu
  startfrage:
    permission: quizcup.frage.start
    description: startet eine frage